modules/admin/controllers/DefaultController.php
<?php

namespace app\modules\admin\controllers;


use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \app\models\Search;
use \app\modules\admin\models\ProgrammeTypes;
use \app\modules\admin\models\UserResult;
use app\modules\admin\models\UserSearchParams;
use yii\helpers\Json;
use app\modules\admin\models\EducationSystem;
/**
 * Default controller for the `admin` module
 */
class DefaultController extends Controller
{
    
    /**
     * @param string           $id
     * @param \yii\base\Module $module
     * @param Finder           $finder
     * @param array            $config
     */
    public function __construct($id, $module, $config = [])
    {
        $this->id = $id;
        $this->module = $module;
        $this->layout = "@app/themes/eac/layouts/dashboard";
        parent::__construct($id, $module, $config);
    }
    /**
     * Renders the index view for the module
     * @return string
     */
    
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['search'],
                'rules' => [
                    [
                        'actions' => ['search' , 'search2' , 'error'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => [],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }
    public function actionSearch()
    {
        $step = 1;
        $search = new Search;
        if ($search->load(Yii::$app->request->post())) {
            
            $search->date_of_search = date('Y-m-d');
            $search->user_id = Yii::$app->user->id;
            if($search->save()){
                 $usersearchparam = new UserSearchParams;
                 $usersearchparam->param_id = 16;
                 $usersearchparam->search_id = $search->search_id;
                 $usersearchparam->param_value = Yii::$app->request->post()['Search']['education_system'];
                if($usersearchparam->save())
                    return $this->redirect(['search2' , 'id' => $search->search_id]);
             }
            
       } 
       return $this->render('search', [
            'user_search_model' => $search,
            'step' => $step
        ]);
   
    }
    
    public function actionSearch2($id)
    {
        $step = 2;
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
            
       } 
       return $this->render('search2', [
            'user_search_model' => $model,
            'step' => $step
        ]);
   
    }
    
    
    public function actionError()
    {
        return $this->render('error');
    }
    
    public function actionSubcat() {
    $out = [];
    
   if (isset($_POST['depdrop_parents'])) {
        $parents = $_POST['depdrop_parents'];
        if ($parents != null) {
            $cat_id = $parents[0];
            $param1 = null;
            $param2 = null;
            if (!empty($_POST['depdrop_params'])) {
                $params = $_POST['depdrop_params'];
                $param1 = $params[0]; // get the value of input-type-1
                $param2 = $params[1]; // get the value of input-type-2
            }
 
            $out = self::getSubCatList1($cat_id, $param1, $param2); 
                 
            
            //$selected = self::getDefaultSubCat($cat_id);
            // the getDefaultSubCat function will query the database
            // and return the default sub cat for the cat_id
            
            echo Json::encode(['output'=>$out, 'selected'=> '']);
            return;
        }
    }
    echo Json::encode(['output'=>'', 'selected'=>'']);
}

protected static function getSubCatList1($id , $param1 , $param2)
{
    $data = [];
   $educs = \app\modules\admin\models\EducationSystem::find()->all();
   foreach ($educs As $item):
       $data[] = ['id'=>$item->system_id, 'name'=>$item->system_name]; 
   endforeach;
    return $data;
}

 protected function findModel($id)
    {
        if (($model = Search::findOne(['search_id'=> $id])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

modules/admin/views/default/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us at <a href="mailto:admin@elimu-services.co.ke">admin@elimu-services.co.ke</a> if you think this is a server error. Thank you.
    </p>

</div>

modules/admin/views/default/index.php
<div class="admin-default-index">
    <h1><?= $this->context->action->uniqueId ?></h1>
    <p>
        This is the view content for action "<?= $this->context->action->id ?>".
        The action belongs to the controller "<?= get_class($this->context) ?>"
        in the "<?= $this->context->module->id ?>" module.
    </p>
    <p>
        You may customize this page by editing the following file:<br>
        <code><?= __FILE__ ?></code>
    </p>
</div>

modules/admin/views/default/search.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\modules\admin\models\ProgrammeTypes;
use app\modules\admin\models\EducationSystem;
use yii\helpers\ArrayHelper;
use kartik\depdrop\DepDrop;

use yii\helpers\Url;
use yii\base\View;

$user = Yii::$app->user->identity;
$this->title = Yii::t('user', 'Search wizard');
$this->params['breadcrumbs'][] = ['label' => "Dashboard", 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => ['search']];
$this->params['breadcrumbs'][] = Yii::t('user', 'Step 1');
$this->params['pageTitle'] = Yii::t('user', 'Search wizard');
?>

<div class="main-content ">
    <div class="row">
        <div class=" col-md-offset-1 col-md-10">
            <!-- PAGE CONTENT BEGINS -->

            <div class="widget-box">
                <div class="widget-header widget-header-green widget-header-flat">
                    <h3 class="widget-title lighter"
                        <i class="ace-icon fa fa-hand-o-right icon-animated-hand-pointer green"></i>
                        <a href="#" class="green"> Career / Courses search wizard Form </a>
                    </h3>
                    <div class="widget-toolbar">
                        <label>
                            <small class="green">
                                <b>Validation</b>
                            </small>

                            <input id="skip-validation" type="checkbox" checked="true" class="ace ace-switch ace-switch-4" />
                            <span class="lbl middle"></span>
                        </label>
                    </div>
                </div>

                <div class="widget-body">
                    <div class="widget-main">
                        <div id="fuelux-wizard-container">
                            <div>
                                <?= $this->render("@app/themes/eac/site/_steps", ['step' => $step]) ?>
                            </div>


                            <hr />

                            <div class="step-content pos-rel">
                                <div class="step-pane active" data-step="1">
                                    <?php
                                    $form = ActiveForm::begin([
                                                'id' => 'search-form',
                                                'enableAjaxValidation' => true,
                                                'validateOnSubmit' => false,
                                                "class" => "form-horizontal"
                                            ])
                                    ?>
                                    <div class="form-group">
                                        <div class="col-xs-12 col-sm-5">
                                            <span class="block input-icon input-icon-right">
                                                <?php $catlist = [1 => 'Professional Career', 2 => 'Undergraduate Programmes', 3 => 'Postgraduate Programmes', 4 => 'Tertiary Institutions', 5 => 'KMTC Medical Courses', 6 => 'Other Colleges'] ?>
                                                <?= $form->field($user_search_model, 'education_cat_id')->dropDownList($catlist, ['prompt' => 'Select ', 'id' => 'education_cat_id']); ?>

                                                <i class="ace-icon fa fa-leaf"></i>
                                            </span>
                                            
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-xs-12 col-sm-5">
                                            <span class="block input-icon input-icon-right">
                                                <?php
                                                // Child # 1
                                                echo $form->field($user_search_model, 'education_system')->widget(DepDrop::classname(), [
                                                    'options' => ['prompt' => 'Select ', 'id' => 'education_system_id'],
                                                    'pluginOptions' => [
                                                        'depends' => ['education_cat_id'], // the id for cat attribute
                                                        'placeholder' => 'Select ...',
                                                        'url' => Url::to(['default/subcat'])
                                                    ]
                                                ]);
                                                ?>

                                                <i class="ace-icon fa fa-wifi"></i>
                                            </span>
                                            
                                        </div>
                                    </div>





                                </div>

                            </div>
                        </div>

                        <div class="modal-footer wizard-actions">

                            <?= Html::submitButton("Next <i class=\"ace-icon fa fa-arrow-right icon-on-right\"></i>", ["class" => "btn btn-success btn-sm btn-next"]) ?>
                            <?= Html::a("Cancel<i class=\"ace-icon fa fa-times\"></i>", Yii::$app->homeUrl, ["class" => "btn btn-danger btn-sm pull-left"]) ?>


                        </div>
                        <?php ActiveForm::end(); ?> 
                    </div>
                </div>
            </div><!-- PAGE CONTENT ENDS -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.main-container -->

<?php
$this->registerCssFile($this->theme->baseUrl . "/assets/css/select2.min.css");
$this->registerCssFile($this->theme->baseUrl . "/css/steps.css");
$this->registerCssFile($this->theme->baseUrl . "/assets/css/chosen.min.css");
$this->registerJsFile($this->theme->baseUrl . "/assets/js/chosen.jquery.min.js");
$this->registerJsFile($this->theme->baseUrl . "/assets/js/select2.min.js");

modules/admin/views/default/search2.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\modules\admin\models\ProgrammeTypes;
use app\modules\admin\models\EducationSystem;
use yii\helpers\ArrayHelper;
use kartik\depdrop\DepDrop;
use yii\helpers\Url;
use yii\base\View;
use app\modules\admin\models\Groups;
use kartik\editable\Editable;
use kartik\select2\Select2;
use kartik\popover\PopoverX;
$user = Yii::$app->user->identity;
$this->title = Yii::t('user', 'Search');
$this->params['breadcrumbs'][] = ['label' => "Dashboard", 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => ['search']];
$this->params['breadcrumbs'][] = Yii::t('user', 'Step 2');
$this->params['pageTitle'] = Yii::t('user', 'Search wizard');
?>

<div class="main-content ">
    <div class="row">
        <div class=" col-md-offset-1 col-md-10">
            <!-- PAGE CONTENT BEGINS -->

            <div class="widget-box">
                <div class="widget-header widget-header-green widget-header-flat">
                    <h3 class="widget-title lighter"
                        <i class="ace-icon fa fa-hand-o-right icon-animated-hand-pointer green"></i>
                        <a href="#" class="green"> Career / Courses search wizard Form </a>
                    </h3>
                    <div class="widget-toolbar">
                        <label>
                            <small class="green">
                                <b>Validation</b>
                            </small>

                            <input id="skip-validation" type="checkbox" checked="true" class="ace ace-switch ace-switch-4" />
                            <span class="lbl middle"></span>
                        </label>
                    </div>
                </div>

                <div class="widget-body">
                    <div class="widget-main">
                        <div id="fuelux-wizard-container">
                            <div>
                                <?= $this->render("@app/themes/eac/site/_steps", ['step' => $step]) ?>
                            </div>


                            <hr />

                            <div class="step-content pos-rel">
                                <div class="step-pane active" data-step="1">
                               
                                 <?php foreach (Groups::find()->all() As $group): ?>
                                    <div class="col-xs-12 col-sm-4 widget-container-col">
                                            <div class="widget-box">
                                                <div class="widget-header">
                                                    <h5 class="widget-title smaller"><?=$group->group_name?></h5>

                                                    <div class="widget-toolbar">
                                                        <span class="label label-success">
                                                            Max
                                                            <?=$group->max_subject?>
                                                            
                                                        </span>
                                                    </div>
                                                </div>

                                                <div class="widget-body">
                                                    <div class="widget-main padding-6">
                                                        <div class="alert alert-info"> 
                                                        <?php
                                                        $model = new \app\modules\admin\models\UserResult;
                                                            $editable = Editable::begin([
                                                                        'model' => $model,
                                                                        'attribute' => 'subject_code',
                                                                        'asPopover' => true,
                                                                        'size' => PopoverX::SIZE_MEDIUM,
                                                                        'inputType' => Editable::INPUT_DEPDROP,
                                                                        'options' => [
                                                                            'type' => DepDrop::TYPE_SELECT2,
                                                                            'select2Options' => ['pluginOptions' => ['allowClear' => true]],
                                                                            'options' => ['id' => "cat-".$group->group_no, 'placeholder' => 'Select grade...'],
                                                                            'pluginOptions' => [
                                                                                'depends' => [$group->group_no],
                                                                                'url' => Url::to(['/site/subcat'])
                                                                            ]
                                                                        ]
                                                            ]);
                                                            $form = $editable->getForm();
// use a hidden input to understand if form is submitted via POST
                                                            $editable->beforeInput = Html::hiddenInput('kv-editable-depdrop', 1) .
                                                                    $form->field($model, 'subject_code')->dropDownList(['' => 'Select subject...'] + app\modules\admin\models\SubjectGroup::findAll("group_no=$group->group_no"), ['id' => $group->group_no])->label(false) . "\n";
                                                                    
                                                            Editable::end();
                                                            ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                   <?php endforeach;?>
                                </div>
                            </div>





                        </div>

                    </div>
                </div>

                <div class="modal-footer wizard-actions">
                    <button class="btn btn-sm btn-prev">
                        <i class="ace-icon fa fa-arrow-left"></i>
                        Prev
                    </button>

                    <button type="submit" class="btn btn-success btn-sm btn-next" data-last="Finish">
                        Next
                        <i class="ace-icon fa fa-arrow-right icon-on-right"></i>
                    </button>

                    <button class="btn btn-danger btn-sm pull-left" data-dismiss="modal">
                        <i class="ace-icon fa fa-times"></i>
                        Cancel
                    </button>
                </div>

            </div>
        </div>
    </div><!-- PAGE CONTENT ENDS -->
</div><!-- /.col -->
</div><!-- /.row -->
</div><!-- /.main-container -->

<?php
$this->registerCssFile($this->theme->baseUrl . "/assets/css/select2.min.css");
$this->registerCssFile($this->theme->baseUrl . "/css/steps.css");
$this->registerJsFile($this->theme->baseUrl . "/assets/js/fuelux.wizard.min.js");
$this->registerJsFile($this->theme->baseUrl . "/assets/js/select2.min.js");